FROM node:12.10-alpine as frontend-builder
WORKDIR /usr/src/app
COPY frontend/package*.json ./
RUN npm install
COPY frontend ./
RUN npm run build

FROM node:12.10-alpine as server-builder
WORKDIR /usr/src
COPY server/package*.json ./server/
RUN cd server && npm install
COPY frontend ./frontend/
COPY server ./server/
RUN cd server && npm run build

FROM node:12.10-alpine
WORKDIR /usr/src/app
COPY server/package*.json ./
RUN npm install --unsafe-perm --only=production
COPY --from=server-builder /usr/src/server/dist ./dist
COPY --from=frontend-builder /usr/src/app/build ./build
ENV NODE_ENV production
EXPOSE 4000
ENTRYPOINT [ "npm", "run", "start:raw" ]